name: Run Tests
on: [push]
jobs:
  test-game-logic:
    runs-on: ubuntu-latest
    # These permissions are needed for the test report
    permissions:
      checks: write
      pull-requests: write
    steps:
      - run: echo "Checking out ${{ github.ref }} from ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run node -v
        run: node -v
      - name: Run npm install
        run: npm install
      - name: Run test
        run: npm run test
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ./junit.xml
